-- ** Database generated with pgModeler (PostgreSQL Database Modeler).
-- ** pgModeler version: 1.2.0
-- ** PostgreSQL version: 17.0
-- ** Project Site: pgmodeler.io
-- ** Model Author: ---
-- object: dbaser | type: ROLE --
-- DROP ROLE IF EXISTS dbaser;
CREATE ROLE dbaser WITH 
	INHERIT
	LOGIN
	 PASSWORD '********';
-- ddl-end --


-- ** Database creation must be performed outside a multi lined SQL file. 
-- ** These commands were put in this file only as a convenience.

-- object: dbieces | type: DATABASE --
-- DROP DATABASE IF EXISTS dbieces;
CREATE DATABASE dbieces
	ENCODING = 'UTF8'
	LC_COLLATE = 'en_US.UTF-8'
	LC_CTYPE = 'en_US.UTF-8'
	TABLESPACE = pg_default
	OWNER = dbaser;
-- ddl-end --


SET search_path TO pg_catalog,public;
-- ddl-end --

-- object: public.django_migrations | type: TABLE --
-- DROP TABLE IF EXISTS public.django_migrations CASCADE;
CREATE TABLE public.django_migrations (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	app character varying(255) NOT NULL,
	name character varying(255) NOT NULL,
	applied timestamp with time zone NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.django_migrations OWNER TO dbaser;
-- ddl-end --

-- object: public.django_content_type | type: TABLE --
-- DROP TABLE IF EXISTS public.django_content_type CASCADE;
CREATE TABLE public.django_content_type (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	app_label character varying(100) NOT NULL,
	model character varying(100) NOT NULL,
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label,model)
);
-- ddl-end --
ALTER TABLE public.django_content_type OWNER TO dbaser;
-- ddl-end --

-- object: public.auth_permission | type: TABLE --
-- DROP TABLE IF EXISTS public.auth_permission CASCADE;
CREATE TABLE public.auth_permission (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	name character varying(255) NOT NULL,
	content_type_id integer NOT NULL,
	codename character varying(100) NOT NULL,
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id,codename)
);
-- ddl-end --
ALTER TABLE public.auth_permission OWNER TO dbaser;
-- ddl-end --

-- object: public.auth_group | type: TABLE --
-- DROP TABLE IF EXISTS public.auth_group CASCADE;
CREATE TABLE public.auth_group (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	name character varying(150) NOT NULL,
	CONSTRAINT auth_group_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_name_key UNIQUE (name)
);
-- ddl-end --
ALTER TABLE public.auth_group OWNER TO dbaser;
-- ddl-end --

-- object: public.auth_group_permissions | type: TABLE --
-- DROP TABLE IF EXISTS public.auth_group_permissions CASCADE;
CREATE TABLE public.auth_group_permissions (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	group_id integer NOT NULL,
	permission_id integer NOT NULL,
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id,permission_id)
);
-- ddl-end --
ALTER TABLE public.auth_group_permissions OWNER TO dbaser;
-- ddl-end --

-- object: public.auth_user | type: TABLE --
-- DROP TABLE IF EXISTS public.auth_user CASCADE;
CREATE TABLE public.auth_user (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	password character varying(128) NOT NULL,
	last_login timestamp with time zone,
	is_superuser boolean NOT NULL,
	username character varying(150) NOT NULL,
	first_name character varying(150) NOT NULL,
	last_name character varying(150) NOT NULL,
	email character varying(254) NOT NULL,
	is_staff boolean NOT NULL,
	is_active boolean NOT NULL,
	date_joined timestamp with time zone NOT NULL,
	CONSTRAINT auth_user_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_username_key UNIQUE (username)
);
-- ddl-end --
ALTER TABLE public.auth_user OWNER TO dbaser;
-- ddl-end --

-- object: public.auth_user_groups | type: TABLE --
-- DROP TABLE IF EXISTS public.auth_user_groups CASCADE;
CREATE TABLE public.auth_user_groups (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	user_id integer NOT NULL,
	group_id integer NOT NULL,
	CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id,group_id)
);
-- ddl-end --
ALTER TABLE public.auth_user_groups OWNER TO dbaser;
-- ddl-end --

-- object: public.auth_user_user_permissions | type: TABLE --
-- DROP TABLE IF EXISTS public.auth_user_user_permissions CASCADE;
CREATE TABLE public.auth_user_user_permissions (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	user_id integer NOT NULL,
	permission_id integer NOT NULL,
	CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id,permission_id)
);
-- ddl-end --
ALTER TABLE public.auth_user_user_permissions OWNER TO dbaser;
-- ddl-end --

-- object: auth_permission_content_type_id_2f476e4b | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_permission_content_type_id_2f476e4b CASCADE;
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission
USING btree
(
	content_type_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_group_permissions_group_id_b120cbf9 | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_group_permissions_group_id_b120cbf9 CASCADE;
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions
USING btree
(
	group_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_group_permissions_permission_id_84c5c92e | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_group_permissions_permission_id_84c5c92e CASCADE;
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions
USING btree
(
	permission_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_user_groups_user_id_6a12ed8b | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_user_groups_user_id_6a12ed8b CASCADE;
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups
USING btree
(
	user_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_user_groups_group_id_97559544 | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_user_groups_group_id_97559544 CASCADE;
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups
USING btree
(
	group_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_user_user_permissions_user_id_a95ead1b | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_user_user_permissions_user_id_a95ead1b CASCADE;
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions
USING btree
(
	user_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_user_user_permissions_permission_id_1fbb5f2c | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_user_user_permissions_permission_id_1fbb5f2c CASCADE;
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions
USING btree
(
	permission_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: public.django_admin_log | type: TABLE --
-- DROP TABLE IF EXISTS public.django_admin_log CASCADE;
CREATE TABLE public.django_admin_log (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	action_time timestamp with time zone NOT NULL,
	object_id text,
	object_repr character varying(200) NOT NULL,
	action_flag smallint NOT NULL,
	change_message text NOT NULL,
	content_type_id integer,
	user_id integer NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.django_admin_log OWNER TO dbaser;
-- ddl-end --

-- object: django_admin_log_content_type_id_c4bce8eb | type: INDEX --
-- DROP INDEX IF EXISTS public.django_admin_log_content_type_id_c4bce8eb CASCADE;
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log
USING btree
(
	content_type_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: django_admin_log_user_id_c564eba6 | type: INDEX --
-- DROP INDEX IF EXISTS public.django_admin_log_user_id_c564eba6 CASCADE;
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log
USING btree
(
	user_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_user_username_6821ab7c_like | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_user_username_6821ab7c_like CASCADE;
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user
USING btree
(
	username
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_group_name_a6ea08ec_like | type: INDEX --
-- DROP INDEX IF EXISTS public.auth_group_name_a6ea08ec_like CASCADE;
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group
USING btree
(
	name
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: public.django_session | type: TABLE --
-- DROP TABLE IF EXISTS public.django_session CASCADE;
CREATE TABLE public.django_session (
	session_key character varying(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamp with time zone NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
-- ddl-end --
ALTER TABLE public.django_session OWNER TO dbaser;
-- ddl-end --

-- object: django_session_session_key_c0390e0f_like | type: INDEX --
-- DROP INDEX IF EXISTS public.django_session_session_key_c0390e0f_like CASCADE;
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session
USING btree
(
	session_key
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: django_session_expire_date_a5c62663 | type: INDEX --
-- DROP INDEX IF EXISTS public.django_session_expire_date_a5c62663 CASCADE;
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session
USING btree
(
	expire_date
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: public.plan | type: TABLE --
-- DROP TABLE IF EXISTS public.plan CASCADE;
CREATE TABLE public.plan (
	id uuid NOT NULL,
	active boolean,
	name character varying(16),
	header character varying(128),
	ordre smallint,
	cta character varying(128),
	year_free_mth smallint,
	first_time_disc smallint,
	monthly_price numeric(10,2) NOT NULL,
	custom_domain boolean,
	mailbox boolean,
	ecommerce boolean,
	vitrine boolean,
	max_users smallint,
	max_clients smallint,
	max_products smallint,
	max_pdfs smallint,
	max_excels smallint,
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT back_tab_plan_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.plan OWNER TO dbaser;
-- ddl-end --

-- object: public.tenant | type: TABLE --
-- DROP TABLE IF EXISTS public.tenant CASCADE;
CREATE TABLE public.tenant (
	id uuid NOT NULL,
	active boolean,
	name character varying(128),
	tel character varying(16),
	email character varying(16),
	phone character varying(16),
	whatsapp character varying(16),
	domain character varying(32),
	slug character varying(32),
	owner character varying(64),
	channel character varying(32),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	CONSTRAINT back_tab_tenant_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.tenant OWNER TO dbaser;
-- ddl-end --

-- object: public."user" | type: TABLE --
-- DROP TABLE IF EXISTS public."user" CASCADE;
CREATE TABLE public."user" (
	id uuid NOT NULL,
	active boolean,
	verified boolean,
	username character varying(16),
	email character varying(64),
	phone character varying(64),
	first_name character varying(64),
	last_name character varying(64),
	is_superuser boolean,
	is_admin boolean,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	tenant_id uuid,
	CONSTRAINT back_tab_user_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public."user" OWNER TO dbaser;
-- ddl-end --

-- object: public.system_payment | type: TABLE --
-- DROP TABLE IF EXISTS public.system_payment CASCADE;
CREATE TABLE public.system_payment (
	id uuid NOT NULL,
	active boolean,
	verified boolean,
	reference character varying(32),
	mode character varying(32),
	date_made date,
	amount numeric(10,2),
	currency character varying(16),
	maker character varying(64),
	note character varying(64),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT back_tab_system_payment_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.system_payment OWNER TO dbaser;
-- ddl-end --

-- object: public.subscription | type: TABLE --
-- DROP TABLE IF EXISTS public.subscription CASCADE;
CREATE TABLE public.subscription (
	id uuid NOT NULL,
	active boolean,
	name character varying(16),
	date_fm date,
	date_to date,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	plan_id uuid,
	payment_id uuid,
	tenant_id uuid,
	owned_by uuid,
	CONSTRAINT back_tab_subscription_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.subscription OWNER TO dbaser;
-- ddl-end --

-- object: public.registre | type: TABLE --
-- DROP TABLE IF EXISTS public.registre CASCADE;
CREATE TABLE public.registre (
	id uuid NOT NULL,
	active boolean,
	date date,
	model character varying(32),
	instance character varying(128),
	operation character varying(1) NOT NULL,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT back_tab_registre_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.registre OWNER TO dbaser;
-- ddl-end --

-- object: back_tab_user_tenant_id_548cf4dd | type: INDEX --
-- DROP INDEX IF EXISTS public.back_tab_user_tenant_id_548cf4dd CASCADE;
CREATE INDEX back_tab_user_tenant_id_548cf4dd ON public."user"
USING btree
(
	tenant_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: back_tab_subscription_plan_id_ca7333fa | type: INDEX --
-- DROP INDEX IF EXISTS public.back_tab_subscription_plan_id_ca7333fa CASCADE;
CREATE INDEX back_tab_subscription_plan_id_ca7333fa ON public.subscription
USING btree
(
	plan_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: back_tab_subscription_payment_id_6e827b93 | type: INDEX --
-- DROP INDEX IF EXISTS public.back_tab_subscription_payment_id_6e827b93 CASCADE;
CREATE INDEX back_tab_subscription_payment_id_6e827b93 ON public.subscription
USING btree
(
	payment_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: back_tab_subscription_tenant_id_e58c9863 | type: INDEX --
-- DROP INDEX IF EXISTS public.back_tab_subscription_tenant_id_e58c9863 CASCADE;
CREATE INDEX back_tab_subscription_tenant_id_e58c9863 ON public.subscription
USING btree
(
	tenant_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: public.category | type: TABLE --
-- DROP TABLE IF EXISTS public.category CASCADE;
CREATE TABLE public.category (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_category_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.category OWNER TO dbaser;
-- ddl-end --

-- object: public.client | type: TABLE --
-- DROP TABLE IF EXISTS public.client CASCADE;
CREATE TABLE public.client (
	id uuid NOT NULL,
	active boolean,
	civilite character varying(1) NOT NULL,
	first_name character varying(64),
	last_name character varying(64) NOT NULL,
	address_l1 character varying(64),
	address_l2 character varying(64),
	address_city character varying(32),
	address_state character varying(32),
	address_country character varying(32),
	address_zip character varying(8),
	tel character varying(16),
	mobile character varying(16),
	whatsapp character varying(16),
	fax character varying(16),
	email character varying(64),
	website character varying(64),
	note character varying(256),
	source character varying(32),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	societe_id uuid,
	CONSTRAINT base_tab_client_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.client OWNER TO dbaser;
-- ddl-end --

-- object: public.clientele | type: TABLE --
-- DROP TABLE IF EXISTS public.clientele CASCADE;
CREATE TABLE public.clientele (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_clientele_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.clientele OWNER TO dbaser;
-- ddl-end --

-- object: public.clientele_client | type: TABLE --
-- DROP TABLE IF EXISTS public.clientele_client CASCADE;
CREATE TABLE public.clientele_client (
	id uuid NOT NULL,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	client_id uuid,
	clientele_id uuid,
	owned_by uuid,
	CONSTRAINT base_tab_clientele_client_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.clientele_client OWNER TO dbaser;
-- ddl-end --

-- object: public.commande | type: TABLE --
-- DROP TABLE IF EXISTS public.commande CASCADE;
CREATE TABLE public.commande (
	id uuid NOT NULL,
	active boolean,
	date_commande date,
	date_livraison date,
	payee boolean,
	status character varying(1) NOT NULL,
	note character varying(256),
	internal_note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	client_id uuid,
	owned_by uuid,
	date_due date,
	file character varying(100),
	gage character varying(64),
	global_discount smallint,
	payment_reminder smallint,
	CONSTRAINT base_tab_commande_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.commande OWNER TO dbaser;
-- ddl-end --

-- object: public.ensemble | type: TABLE --
-- DROP TABLE IF EXISTS public.ensemble CASCADE;
CREATE TABLE public.ensemble (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_ensemble_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.ensemble OWNER TO dbaser;
-- ddl-end --

-- object: public.fabricant | type: TABLE --
-- DROP TABLE IF EXISTS public.fabricant CASCADE;
CREATE TABLE public.fabricant (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	country character varying(16),
	website character varying(128),
	contact character varying(16),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_fabricant_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.fabricant OWNER TO dbaser;
-- ddl-end --

-- object: public.fournisseur | type: TABLE --
-- DROP TABLE IF EXISTS public.fournisseur CASCADE;
CREATE TABLE public.fournisseur (
	id uuid NOT NULL,
	active boolean,
	name character varying(128) NOT NULL,
	address_l1 character varying(64),
	address_l2 character varying(64),
	address_city character varying(32),
	address_state character varying(32),
	address_country character varying(32),
	address_zip character varying(8),
	tel character varying(16),
	mobile character varying(16),
	whatsapp character varying(16),
	fax character varying(16),
	email character varying(64),
	website character varying(64),
	note character varying(256),
	source character varying(32),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	societe_id uuid,
	CONSTRAINT base_tab_fournisseur_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.fournisseur OWNER TO dbaser;
-- ddl-end --

-- object: public."group" | type: TABLE --
-- DROP TABLE IF EXISTS public."group" CASCADE;
CREATE TABLE public."group" (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_group_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public."group" OWNER TO dbaser;
-- ddl-end --

-- object: public.magasin | type: TABLE --
-- DROP TABLE IF EXISTS public.magasin CASCADE;
CREATE TABLE public.magasin (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	address character varying(64),
	city character varying(16),
	state character varying(16),
	country character varying(16),
	website character varying(128),
	manager character varying(128),
	contact character varying(128),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_magasin_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.magasin OWNER TO dbaser;
-- ddl-end --

-- object: public.floor | type: TABLE --
-- DROP TABLE IF EXISTS public.floor CASCADE;
CREATE TABLE public.floor (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	elevation smallint,
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	magasin_id uuid,
	CONSTRAINT base_tab_floor_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.floor OWNER TO dbaser;
-- ddl-end --

-- object: public.payment | type: TABLE --
-- DROP TABLE IF EXISTS public.payment CASCADE;
CREATE TABLE public.payment (
	id uuid NOT NULL,
	active boolean,
	verified boolean,
	reference character varying(32),
	mode character varying(32),
	date_made date,
	amount numeric(10,2),
	currency character varying(16),
	maker character varying(64),
	note character varying(64),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	commande_id uuid,
	owned_by uuid,
	CONSTRAINT base_tab_payment_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.payment OWNER TO dbaser;
-- ddl-end --

-- object: public.product | type: TABLE --
-- DROP TABLE IF EXISTS public.product CASCADE;
CREATE TABLE public.product (
	id uuid NOT NULL,
	active boolean,
	reference character varying(64),
	name character varying(128) NOT NULL,
	condition character varying(1) NOT NULL,
	um character varying(16),
	sku character varying(128),
	origin character varying(32),
	barcode character varying(256),
	tva_percent smallint,
	prix_vente_public smallint,
	prix_vente_online smallint,
	list_online boolean,
	max_discount smallint,
	dimension_l_cm smallint,
	dimension_w_cm smallint,
	dimension_h_cm smallint,
	weight_kg numeric(6,2),
	expires boolean,
	fragile boolean,
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	fabricant_id uuid,
	group_id uuid,
	owned_by uuid,
	guarantee smallint,
	CONSTRAINT base_tab_product_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.product OWNER TO dbaser;
-- ddl-end --

-- object: public.file | type: TABLE --
-- DROP TABLE IF EXISTS public.file CASCADE;
CREATE TABLE public.file (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	upload character varying(100),
	mime character varying(32),
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	product_id uuid,
	CONSTRAINT base_tab_file_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.file OWNER TO dbaser;
-- ddl-end --

-- object: public.ensemble_product | type: TABLE --
-- DROP TABLE IF EXISTS public.ensemble_product CASCADE;
CREATE TABLE public.ensemble_product (
	id uuid NOT NULL,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	ensemble_id uuid,
	owned_by uuid,
	product_id uuid,
	CONSTRAINT base_tab_ensemble_product_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.ensemble_product OWNER TO dbaser;
-- ddl-end --

-- object: public.category_product | type: TABLE --
-- DROP TABLE IF EXISTS public.category_product CASCADE;
CREATE TABLE public.category_product (
	id uuid NOT NULL,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	category_id uuid,
	owned_by uuid,
	product_id uuid,
	CONSTRAINT base_tab_category_product_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.category_product OWNER TO dbaser;
-- ddl-end --

-- object: public.rayon | type: TABLE --
-- DROP TABLE IF EXISTS public.rayon CASCADE;
CREATE TABLE public.rayon (
	id uuid NOT NULL,
	active boolean,
	name character varying(64),
	number smallint,
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	floor_id uuid,
	owned_by uuid,
	CONSTRAINT base_tab_rayon_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.rayon OWNER TO dbaser;
-- ddl-end --

-- object: public.reception | type: TABLE --
-- DROP TABLE IF EXISTS public.reception CASCADE;
CREATE TABLE public.reception (
	id uuid NOT NULL,
	date_commande date,
	date_livraison date NOT NULL,
	active boolean,
	payee boolean,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	fournisseur_id uuid,
	owned_by uuid,
	date_due date,
	gage character varying(64),
	payment_reminder smallint,
	CONSTRAINT base_tab_reception_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.reception OWNER TO dbaser;
-- ddl-end --

-- object: public.entree | type: TABLE --
-- DROP TABLE IF EXISTS public.entree CASCADE;
CREATE TABLE public.entree (
	id uuid NOT NULL,
	quantity smallint,
	prix_unit smallint,
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	product_id uuid,
	rayon_id uuid,
	reception_id uuid,
	CONSTRAINT base_tab_entree_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.entree OWNER TO dbaser;
-- ddl-end --

-- object: public.societe | type: TABLE --
-- DROP TABLE IF EXISTS public.societe CASCADE;
CREATE TABLE public.societe (
	id uuid NOT NULL,
	active boolean,
	raison_social character varying(128),
	forme character varying(1) NOT NULL,
	ice character varying(64),
	rc character varying(64),
	tp character varying(64),
	rib character varying(64),
	city character varying(64),
	state character varying(64),
	country character varying(64),
	manager character varying(64),
	date_est date,
	sector character varying(128),
	phone character varying(16),
	fax character varying(16),
	email character varying(64),
	website character varying(64),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_societe_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.societe OWNER TO dbaser;
-- ddl-end --

-- object: public.sortie | type: TABLE --
-- DROP TABLE IF EXISTS public.sortie CASCADE;
CREATE TABLE public.sortie (
	id uuid NOT NULL,
	qtte_cmde smallint,
	qtte_recv smallint,
	prix_unit smallint,
	discount smallint,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	commande_id uuid,
	owned_by uuid,
	product_id uuid,
	rayon_id uuid,
	CONSTRAINT base_tab_sortie_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.sortie OWNER TO dbaser;
-- ddl-end --

-- object: public.stock | type: TABLE --
-- DROP TABLE IF EXISTS public.stock CASCADE;
CREATE TABLE public.stock (
	id uuid NOT NULL,
	quantity smallint,
	note character varying(256),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	magasin_id uuid,
	owned_by uuid,
	product_id uuid,
	CONSTRAINT base_tab_stock_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.stock OWNER TO dbaser;
-- ddl-end --

-- object: public.vehicule | type: TABLE --
-- DROP TABLE IF EXISTS public.vehicule CASCADE;
CREATE TABLE public.vehicule (
	id uuid NOT NULL,
	active boolean,
	marque character varying(16),
	model_nom character varying(16),
	model_code character varying(16),
	year_start date,
	year_end date,
	category character varying(16),
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	CONSTRAINT base_tab_vehicule_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.vehicule OWNER TO dbaser;
-- ddl-end --

-- object: public.vehicule_product | type: TABLE --
-- DROP TABLE IF EXISTS public.vehicule_product CASCADE;
CREATE TABLE public.vehicule_product (
	id uuid NOT NULL,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	owned_by uuid,
	product_id uuid,
	vehicule_id uuid,
	CONSTRAINT base_tab_vehicule_product_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.vehicule_product OWNER TO dbaser;
-- ddl-end --

-- object: base_tab_clientele_client_client_id_78d83261 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_clientele_client_client_id_78d83261 CASCADE;
CREATE INDEX base_tab_clientele_client_client_id_78d83261 ON public.clientele_client
USING btree
(
	client_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_clientele_client_clientele_id_1ea9946a | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_clientele_client_clientele_id_1ea9946a CASCADE;
CREATE INDEX base_tab_clientele_client_clientele_id_1ea9946a ON public.clientele_client
USING btree
(
	clientele_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_commande_client_id_83037807 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_commande_client_id_83037807 CASCADE;
CREATE INDEX base_tab_commande_client_id_83037807 ON public.commande
USING btree
(
	client_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_floor_magasin_id_2474c58c | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_floor_magasin_id_2474c58c CASCADE;
CREATE INDEX base_tab_floor_magasin_id_2474c58c ON public.floor
USING btree
(
	magasin_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_payment_commande_id_f5e5f4b8 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_payment_commande_id_f5e5f4b8 CASCADE;
CREATE INDEX base_tab_payment_commande_id_f5e5f4b8 ON public.payment
USING btree
(
	commande_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_product_fabricant_id_4f3265d1 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_product_fabricant_id_4f3265d1 CASCADE;
CREATE INDEX base_tab_product_fabricant_id_4f3265d1 ON public.product
USING btree
(
	fabricant_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_product_group_id_02c415d6 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_product_group_id_02c415d6 CASCADE;
CREATE INDEX base_tab_product_group_id_02c415d6 ON public.product
USING btree
(
	group_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_file_product_id_868fe664 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_file_product_id_868fe664 CASCADE;
CREATE INDEX base_tab_file_product_id_868fe664 ON public.file
USING btree
(
	product_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_ensemble_product_ensemble_id_3349a328 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_ensemble_product_ensemble_id_3349a328 CASCADE;
CREATE INDEX base_tab_ensemble_product_ensemble_id_3349a328 ON public.ensemble_product
USING btree
(
	ensemble_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_ensemble_product_product_id_cc5f1fc1 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_ensemble_product_product_id_cc5f1fc1 CASCADE;
CREATE INDEX base_tab_ensemble_product_product_id_cc5f1fc1 ON public.ensemble_product
USING btree
(
	product_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_category_product_category_id_7d5e7cde | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_category_product_category_id_7d5e7cde CASCADE;
CREATE INDEX base_tab_category_product_category_id_7d5e7cde ON public.category_product
USING btree
(
	category_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_category_product_product_id_b486db98 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_category_product_product_id_b486db98 CASCADE;
CREATE INDEX base_tab_category_product_product_id_b486db98 ON public.category_product
USING btree
(
	product_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_rayon_floor_id_018447b9 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_rayon_floor_id_018447b9 CASCADE;
CREATE INDEX base_tab_rayon_floor_id_018447b9 ON public.rayon
USING btree
(
	floor_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_reception_fournisseur_id_90ef4a79 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_reception_fournisseur_id_90ef4a79 CASCADE;
CREATE INDEX base_tab_reception_fournisseur_id_90ef4a79 ON public.reception
USING btree
(
	fournisseur_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_entree_product_id_ee3b32d5 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_entree_product_id_ee3b32d5 CASCADE;
CREATE INDEX base_tab_entree_product_id_ee3b32d5 ON public.entree
USING btree
(
	product_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_entree_rayon_id_9f66f859 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_entree_rayon_id_9f66f859 CASCADE;
CREATE INDEX base_tab_entree_rayon_id_9f66f859 ON public.entree
USING btree
(
	rayon_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_entree_reception_id_c34aa2b0 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_entree_reception_id_c34aa2b0 CASCADE;
CREATE INDEX base_tab_entree_reception_id_c34aa2b0 ON public.entree
USING btree
(
	reception_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_fournisseur_societe_id_569a95d3 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_fournisseur_societe_id_569a95d3 CASCADE;
CREATE INDEX base_tab_fournisseur_societe_id_569a95d3 ON public.fournisseur
USING btree
(
	societe_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_client_societe_id_69c93900 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_client_societe_id_69c93900 CASCADE;
CREATE INDEX base_tab_client_societe_id_69c93900 ON public.client
USING btree
(
	societe_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_sortie_commande_id_c111d1a0 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_sortie_commande_id_c111d1a0 CASCADE;
CREATE INDEX base_tab_sortie_commande_id_c111d1a0 ON public.sortie
USING btree
(
	commande_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_sortie_product_id_66a9a982 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_sortie_product_id_66a9a982 CASCADE;
CREATE INDEX base_tab_sortie_product_id_66a9a982 ON public.sortie
USING btree
(
	product_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_sortie_rayon_id_fe4118dd | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_sortie_rayon_id_fe4118dd CASCADE;
CREATE INDEX base_tab_sortie_rayon_id_fe4118dd ON public.sortie
USING btree
(
	rayon_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_stock_magasin_id_477115e7 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_stock_magasin_id_477115e7 CASCADE;
CREATE INDEX base_tab_stock_magasin_id_477115e7 ON public.stock
USING btree
(
	magasin_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_stock_product_id_125d2ad5 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_stock_product_id_125d2ad5 CASCADE;
CREATE INDEX base_tab_stock_product_id_125d2ad5 ON public.stock
USING btree
(
	product_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_vehicule_product_product_id_b3943362 | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_vehicule_product_product_id_b3943362 CASCADE;
CREATE INDEX base_tab_vehicule_product_product_id_b3943362 ON public.vehicule_product
USING btree
(
	product_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: base_tab_vehicule_product_vehicule_id_428eb3ce | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_vehicule_product_vehicule_id_428eb3ce CASCADE;
CREATE INDEX base_tab_vehicule_product_vehicule_id_428eb3ce ON public.vehicule_product
USING btree
(
	vehicule_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: public.constant | type: TABLE --
-- DROP TABLE IF EXISTS public.constant CASCADE;
CREATE TABLE public.constant (
	id uuid NOT NULL,
	active boolean,
	key character varying(32),
	name character varying(64),
	note character varying(256),
	value character varying(256),
	owned_by uuid,
	created_by uuid,
	created_on timestamp with time zone,
	edited_by uuid,
	edited_on timestamp with time zone,
	tenant_id uuid,
	CONSTRAINT base_tab_constant_pkey PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.constant OWNER TO dbaser;
-- ddl-end --

-- object: base_tab_constant_tenant_id_ccbe052a | type: INDEX --
-- DROP INDEX IF EXISTS public.base_tab_constant_tenant_id_ccbe052a CASCADE;
CREATE INDEX base_tab_constant_tenant_id_ccbe052a ON public.constant
USING btree
(
	tenant_id
)
WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: auth_permission_content_type_id_2f476e4b_fk_django_co | type: CONSTRAINT --
-- ALTER TABLE public.auth_permission DROP CONSTRAINT IF EXISTS auth_permission_content_type_id_2f476e4b_fk_django_co CASCADE;
ALTER TABLE public.auth_permission ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
REFERENCES public.django_content_type (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: auth_group_permissions_group_id_b120cbf9_fk_auth_group_id | type: CONSTRAINT --
-- ALTER TABLE public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissions_group_id_b120cbf9_fk_auth_group_id CASCADE;
ALTER TABLE public.auth_group_permissions ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
REFERENCES public.auth_group (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: auth_group_permissio_permission_id_84c5c92e_fk_auth_perm | type: CONSTRAINT --
-- ALTER TABLE public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissio_permission_id_84c5c92e_fk_auth_perm CASCADE;
ALTER TABLE public.auth_group_permissions ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
REFERENCES public.auth_permission (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: auth_user_groups_user_id_6a12ed8b_fk_auth_user_id | type: CONSTRAINT --
-- ALTER TABLE public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_user_id_6a12ed8b_fk_auth_user_id CASCADE;
ALTER TABLE public.auth_user_groups ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
REFERENCES public.auth_user (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: auth_user_groups_group_id_97559544_fk_auth_group_id | type: CONSTRAINT --
-- ALTER TABLE public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_group_id_97559544_fk_auth_group_id CASCADE;
ALTER TABLE public.auth_user_groups ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
REFERENCES public.auth_group (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id | type: CONSTRAINT --
-- ALTER TABLE public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id CASCADE;
ALTER TABLE public.auth_user_user_permissions ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
REFERENCES public.auth_user (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm | type: CONSTRAINT --
-- ALTER TABLE public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm CASCADE;
ALTER TABLE public.auth_user_user_permissions ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
REFERENCES public.auth_permission (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: django_admin_log_content_type_id_c4bce8eb_fk_django_co | type: CONSTRAINT --
-- ALTER TABLE public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_content_type_id_c4bce8eb_fk_django_co CASCADE;
ALTER TABLE public.django_admin_log ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
REFERENCES public.django_content_type (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: django_admin_log_user_id_c564eba6_fk_auth_user_id | type: CONSTRAINT --
-- ALTER TABLE public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id CASCADE;
ALTER TABLE public.django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
REFERENCES public.auth_user (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: back_tab_user_tenant_id_548cf4dd_fk_back_tab_tenant_id | type: CONSTRAINT --
-- ALTER TABLE public."user" DROP CONSTRAINT IF EXISTS back_tab_user_tenant_id_548cf4dd_fk_back_tab_tenant_id CASCADE;
ALTER TABLE public."user" ADD CONSTRAINT back_tab_user_tenant_id_548cf4dd_fk_back_tab_tenant_id FOREIGN KEY (tenant_id)
REFERENCES public.tenant (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: back_tab_subscription_plan_id_ca7333fa_fk_back_tab_plan_id | type: CONSTRAINT --
-- ALTER TABLE public.subscription DROP CONSTRAINT IF EXISTS back_tab_subscription_plan_id_ca7333fa_fk_back_tab_plan_id CASCADE;
ALTER TABLE public.subscription ADD CONSTRAINT back_tab_subscription_plan_id_ca7333fa_fk_back_tab_plan_id FOREIGN KEY (plan_id)
REFERENCES public.plan (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: back_tab_subscriptio_payment_id_6e827b93_fk_back_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.subscription DROP CONSTRAINT IF EXISTS back_tab_subscriptio_payment_id_6e827b93_fk_back_tab_ CASCADE;
ALTER TABLE public.subscription ADD CONSTRAINT back_tab_subscriptio_payment_id_6e827b93_fk_back_tab_ FOREIGN KEY (payment_id)
REFERENCES public.system_payment (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: back_tab_subscription_tenant_id_e58c9863_fk_back_tab_tenant_id | type: CONSTRAINT --
-- ALTER TABLE public.subscription DROP CONSTRAINT IF EXISTS back_tab_subscription_tenant_id_e58c9863_fk_back_tab_tenant_id CASCADE;
ALTER TABLE public.subscription ADD CONSTRAINT back_tab_subscription_tenant_id_e58c9863_fk_back_tab_tenant_id FOREIGN KEY (tenant_id)
REFERENCES public.tenant (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_client_societe_id_69c93900_fk_base_tab_societe_id | type: CONSTRAINT --
-- ALTER TABLE public.client DROP CONSTRAINT IF EXISTS base_tab_client_societe_id_69c93900_fk_base_tab_societe_id CASCADE;
ALTER TABLE public.client ADD CONSTRAINT base_tab_client_societe_id_69c93900_fk_base_tab_societe_id FOREIGN KEY (societe_id)
REFERENCES public.societe (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_clientele_c_client_id_78d83261_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.clientele_client DROP CONSTRAINT IF EXISTS base_tab_clientele_c_client_id_78d83261_fk_base_tab_ CASCADE;
ALTER TABLE public.clientele_client ADD CONSTRAINT base_tab_clientele_c_client_id_78d83261_fk_base_tab_ FOREIGN KEY (client_id)
REFERENCES public.client (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_clientele_c_clientele_id_1ea9946a_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.clientele_client DROP CONSTRAINT IF EXISTS base_tab_clientele_c_clientele_id_1ea9946a_fk_base_tab_ CASCADE;
ALTER TABLE public.clientele_client ADD CONSTRAINT base_tab_clientele_c_clientele_id_1ea9946a_fk_base_tab_ FOREIGN KEY (clientele_id)
REFERENCES public.clientele (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_commande_client_id_83037807_fk_base_tab_client_id | type: CONSTRAINT --
-- ALTER TABLE public.commande DROP CONSTRAINT IF EXISTS base_tab_commande_client_id_83037807_fk_base_tab_client_id CASCADE;
ALTER TABLE public.commande ADD CONSTRAINT base_tab_commande_client_id_83037807_fk_base_tab_client_id FOREIGN KEY (client_id)
REFERENCES public.client (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_fournisseur_societe_id_569a95d3_fk_base_tab_societe_id | type: CONSTRAINT --
-- ALTER TABLE public.fournisseur DROP CONSTRAINT IF EXISTS base_tab_fournisseur_societe_id_569a95d3_fk_base_tab_societe_id CASCADE;
ALTER TABLE public.fournisseur ADD CONSTRAINT base_tab_fournisseur_societe_id_569a95d3_fk_base_tab_societe_id FOREIGN KEY (societe_id)
REFERENCES public.societe (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_floor_magasin_id_2474c58c_fk_base_tab_magasin_id | type: CONSTRAINT --
-- ALTER TABLE public.floor DROP CONSTRAINT IF EXISTS base_tab_floor_magasin_id_2474c58c_fk_base_tab_magasin_id CASCADE;
ALTER TABLE public.floor ADD CONSTRAINT base_tab_floor_magasin_id_2474c58c_fk_base_tab_magasin_id FOREIGN KEY (magasin_id)
REFERENCES public.magasin (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_payment_commande_id_f5e5f4b8_fk_base_tab_commande_id | type: CONSTRAINT --
-- ALTER TABLE public.payment DROP CONSTRAINT IF EXISTS base_tab_payment_commande_id_f5e5f4b8_fk_base_tab_commande_id CASCADE;
ALTER TABLE public.payment ADD CONSTRAINT base_tab_payment_commande_id_f5e5f4b8_fk_base_tab_commande_id FOREIGN KEY (commande_id)
REFERENCES public.commande (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_product_fabricant_id_4f3265d1_fk_base_tab_fabricant_id | type: CONSTRAINT --
-- ALTER TABLE public.product DROP CONSTRAINT IF EXISTS base_tab_product_fabricant_id_4f3265d1_fk_base_tab_fabricant_id CASCADE;
ALTER TABLE public.product ADD CONSTRAINT base_tab_product_fabricant_id_4f3265d1_fk_base_tab_fabricant_id FOREIGN KEY (fabricant_id)
REFERENCES public.fabricant (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_product_group_id_02c415d6_fk_base_tab_group_id | type: CONSTRAINT --
-- ALTER TABLE public.product DROP CONSTRAINT IF EXISTS base_tab_product_group_id_02c415d6_fk_base_tab_group_id CASCADE;
ALTER TABLE public.product ADD CONSTRAINT base_tab_product_group_id_02c415d6_fk_base_tab_group_id FOREIGN KEY (group_id)
REFERENCES public."group" (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_file_product_id_868fe664_fk_base_tab_product_id | type: CONSTRAINT --
-- ALTER TABLE public.file DROP CONSTRAINT IF EXISTS base_tab_file_product_id_868fe664_fk_base_tab_product_id CASCADE;
ALTER TABLE public.file ADD CONSTRAINT base_tab_file_product_id_868fe664_fk_base_tab_product_id FOREIGN KEY (product_id)
REFERENCES public.product (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_ensemble_pr_ensemble_id_3349a328_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.ensemble_product DROP CONSTRAINT IF EXISTS base_tab_ensemble_pr_ensemble_id_3349a328_fk_base_tab_ CASCADE;
ALTER TABLE public.ensemble_product ADD CONSTRAINT base_tab_ensemble_pr_ensemble_id_3349a328_fk_base_tab_ FOREIGN KEY (ensemble_id)
REFERENCES public.ensemble (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_ensemble_pr_product_id_cc5f1fc1_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.ensemble_product DROP CONSTRAINT IF EXISTS base_tab_ensemble_pr_product_id_cc5f1fc1_fk_base_tab_ CASCADE;
ALTER TABLE public.ensemble_product ADD CONSTRAINT base_tab_ensemble_pr_product_id_cc5f1fc1_fk_base_tab_ FOREIGN KEY (product_id)
REFERENCES public.product (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_category_pr_category_id_7d5e7cde_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.category_product DROP CONSTRAINT IF EXISTS base_tab_category_pr_category_id_7d5e7cde_fk_base_tab_ CASCADE;
ALTER TABLE public.category_product ADD CONSTRAINT base_tab_category_pr_category_id_7d5e7cde_fk_base_tab_ FOREIGN KEY (category_id)
REFERENCES public.category (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_category_pr_product_id_b486db98_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.category_product DROP CONSTRAINT IF EXISTS base_tab_category_pr_product_id_b486db98_fk_base_tab_ CASCADE;
ALTER TABLE public.category_product ADD CONSTRAINT base_tab_category_pr_product_id_b486db98_fk_base_tab_ FOREIGN KEY (product_id)
REFERENCES public.product (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_rayon_floor_id_018447b9_fk_base_tab_floor_id | type: CONSTRAINT --
-- ALTER TABLE public.rayon DROP CONSTRAINT IF EXISTS base_tab_rayon_floor_id_018447b9_fk_base_tab_floor_id CASCADE;
ALTER TABLE public.rayon ADD CONSTRAINT base_tab_rayon_floor_id_018447b9_fk_base_tab_floor_id FOREIGN KEY (floor_id)
REFERENCES public.floor (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_reception_fournisseur_id_90ef4a79_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.reception DROP CONSTRAINT IF EXISTS base_tab_reception_fournisseur_id_90ef4a79_fk_base_tab_ CASCADE;
ALTER TABLE public.reception ADD CONSTRAINT base_tab_reception_fournisseur_id_90ef4a79_fk_base_tab_ FOREIGN KEY (fournisseur_id)
REFERENCES public.fournisseur (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_entree_product_id_ee3b32d5_fk_base_tab_product_id | type: CONSTRAINT --
-- ALTER TABLE public.entree DROP CONSTRAINT IF EXISTS base_tab_entree_product_id_ee3b32d5_fk_base_tab_product_id CASCADE;
ALTER TABLE public.entree ADD CONSTRAINT base_tab_entree_product_id_ee3b32d5_fk_base_tab_product_id FOREIGN KEY (product_id)
REFERENCES public.product (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_entree_rayon_id_9f66f859_fk_base_tab_rayon_id | type: CONSTRAINT --
-- ALTER TABLE public.entree DROP CONSTRAINT IF EXISTS base_tab_entree_rayon_id_9f66f859_fk_base_tab_rayon_id CASCADE;
ALTER TABLE public.entree ADD CONSTRAINT base_tab_entree_rayon_id_9f66f859_fk_base_tab_rayon_id FOREIGN KEY (rayon_id)
REFERENCES public.rayon (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_entree_reception_id_c34aa2b0_fk_base_tab_reception_id | type: CONSTRAINT --
-- ALTER TABLE public.entree DROP CONSTRAINT IF EXISTS base_tab_entree_reception_id_c34aa2b0_fk_base_tab_reception_id CASCADE;
ALTER TABLE public.entree ADD CONSTRAINT base_tab_entree_reception_id_c34aa2b0_fk_base_tab_reception_id FOREIGN KEY (reception_id)
REFERENCES public.reception (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_sortie_commande_id_c111d1a0_fk_base_tab_commande_id | type: CONSTRAINT --
-- ALTER TABLE public.sortie DROP CONSTRAINT IF EXISTS base_tab_sortie_commande_id_c111d1a0_fk_base_tab_commande_id CASCADE;
ALTER TABLE public.sortie ADD CONSTRAINT base_tab_sortie_commande_id_c111d1a0_fk_base_tab_commande_id FOREIGN KEY (commande_id)
REFERENCES public.commande (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_sortie_product_id_66a9a982_fk_base_tab_product_id | type: CONSTRAINT --
-- ALTER TABLE public.sortie DROP CONSTRAINT IF EXISTS base_tab_sortie_product_id_66a9a982_fk_base_tab_product_id CASCADE;
ALTER TABLE public.sortie ADD CONSTRAINT base_tab_sortie_product_id_66a9a982_fk_base_tab_product_id FOREIGN KEY (product_id)
REFERENCES public.product (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_sortie_rayon_id_fe4118dd_fk_base_tab_rayon_id | type: CONSTRAINT --
-- ALTER TABLE public.sortie DROP CONSTRAINT IF EXISTS base_tab_sortie_rayon_id_fe4118dd_fk_base_tab_rayon_id CASCADE;
ALTER TABLE public.sortie ADD CONSTRAINT base_tab_sortie_rayon_id_fe4118dd_fk_base_tab_rayon_id FOREIGN KEY (rayon_id)
REFERENCES public.rayon (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_stock_magasin_id_477115e7_fk_base_tab_magasin_id | type: CONSTRAINT --
-- ALTER TABLE public.stock DROP CONSTRAINT IF EXISTS base_tab_stock_magasin_id_477115e7_fk_base_tab_magasin_id CASCADE;
ALTER TABLE public.stock ADD CONSTRAINT base_tab_stock_magasin_id_477115e7_fk_base_tab_magasin_id FOREIGN KEY (magasin_id)
REFERENCES public.magasin (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_stock_product_id_125d2ad5_fk_base_tab_product_id | type: CONSTRAINT --
-- ALTER TABLE public.stock DROP CONSTRAINT IF EXISTS base_tab_stock_product_id_125d2ad5_fk_base_tab_product_id CASCADE;
ALTER TABLE public.stock ADD CONSTRAINT base_tab_stock_product_id_125d2ad5_fk_base_tab_product_id FOREIGN KEY (product_id)
REFERENCES public.product (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_vehicule_pr_product_id_b3943362_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.vehicule_product DROP CONSTRAINT IF EXISTS base_tab_vehicule_pr_product_id_b3943362_fk_base_tab_ CASCADE;
ALTER TABLE public.vehicule_product ADD CONSTRAINT base_tab_vehicule_pr_product_id_b3943362_fk_base_tab_ FOREIGN KEY (product_id)
REFERENCES public.product (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_vehicule_pr_vehicule_id_428eb3ce_fk_base_tab_ | type: CONSTRAINT --
-- ALTER TABLE public.vehicule_product DROP CONSTRAINT IF EXISTS base_tab_vehicule_pr_vehicule_id_428eb3ce_fk_base_tab_ CASCADE;
ALTER TABLE public.vehicule_product ADD CONSTRAINT base_tab_vehicule_pr_vehicule_id_428eb3ce_fk_base_tab_ FOREIGN KEY (vehicule_id)
REFERENCES public.vehicule (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --

-- object: base_tab_constant_tenant_id_ccbe052a_fk_back_tab_tenant_id | type: CONSTRAINT --
-- ALTER TABLE public.constant DROP CONSTRAINT IF EXISTS base_tab_constant_tenant_id_ccbe052a_fk_back_tab_tenant_id CASCADE;
ALTER TABLE public.constant ADD CONSTRAINT base_tab_constant_tenant_id_ccbe052a_fk_back_tab_tenant_id FOREIGN KEY (tenant_id)
REFERENCES public.tenant (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
-- ddl-end --


